remote_theme: "mmistakes/jekyll-theme-basically-basic"
lang: en
description: Another Tetris clone
url: https://github.com/adrienmalin/TETRIS2000
author: Adrien Malingre
logo: https://raw.githubusercontent.com/adrienmalin/Tetris2000/master/icons/48.png
github_username: adrienmalin
